name: Test workflow choices
on:
    workflow_dispatch:
        inputs:
            deploy_pl_node:
                description: deploy pl node
                required: true
                type: boolean
                default: true
            deploy_all_other_nodes:
                description: deploy all other nodes
                type: boolean
                required: true
                default: true

jobs:
    test_pl:
        name: test pl
        runs-on: ubuntu-latest
        if: github.event.inputs.deploy_pl_node
        steps:
            - name: echo pl node
              run:
                echo "hello world ${{ github.event.inputs.deploy_pl_node }}"
    test_other:
        name: test other
        runs-on: ubuntu-latest
        if: github.event.inputs.deploy_all_other_nodes
        steps:
            - name: echo all other nodes
              run:
                echo "hello world ${{ github.event.inputs.deploy_all_other_nodes }}"
